# -*- coding: utf-8 -*-
"""NumPY Practice  (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Pt0vSqf4PsMLgJJztxO_G2S8xnZDceDJ

# Import NumPY Library
"""

import numpy as np

"""# Creating a NumPy Array

## Basic ndarray
"""

a = [10,20,30,40]

type(a)

x = np.array(a)

print(x)

type(x)

a = [1,2,3,4]
b = [10,20,30,40]
x = np.array([a,b])

print(x)

a = [1,2,3,]
b = [10,20,30]
x = np.array([a,b])

print(x)

x = np.array([1,2,3,4], dtype = np.float32)
print(x)

x = np.zeros((2,3))
print(x)

"""## Array of zeros"""

x = np.zeros((4,4))
print(x)

"""## Array of ones"""

np.ones((3,3))

np.ones(5, dtype = np.int32)

"""## Random numbers in ndarrays"""

x = np.random.rand(2,5)

print(x)

np.random.rand??

np.random.randint(1,20, size = (3,3))

np.random.randint??

np.random.randn(2,5)

np.random.randn??

np.random.choice([2,3,4,7,8,10])

"""## An array of your choice"""

np.full((3,4),10)

np.ones((3,3))*10

"""## Identity matrix"""

x = np.eye(4, k = -1)
print(x)

np.eye??

"""## Evenly spaced ndarray"""

np.arange(5,11)

np.arange(0,11,2)

np.linspace(0,1,5)

"""# $\frac{end-start}{n-1}$

# Shape and Reshaping of NumPy Array

## Dimension of nparray
"""

a = [10,20,30,40,50]
x = np.array(a)
print(x)

x.ndim

b = [1,2,3,4,5]
y = np.array([a,b])
print(y)

y.ndim

"""## Shape of NumPy array"""

y.shape

y.size

"""## Reshaping a NumPy array"""

a = np.array([3,6,9,12])
print(a)

np.reshape(a, (2,2))

a.reshape(2,2)

x = np.arange(1,16)
x

x.size

x.reshape(5,3)

"""## Transpose of a NumPy array"""

x = np.arange(1,16)
print(x)

y = x.reshape(3,5)
print(y)

z = np.transpose(y)
print(z)

y.transpose()

"""# Indexing and Slicing of NumPy Array

## 1D NumPy arrays
"""

a = np.arange(1,10)

print(a)

a[2:6]

"""## 2-D NumPy arrays"""

x = np.arange(1,10).reshape(3,3)
print(x)

x[1,2]

x[1][2]

x[1:3,1:3]

"""# Stacking and Concatenating NumPy Arrays

## Stacking
"""

a = np.arange(1,6)
b = np.arange(6,11)

print(a)

print(b)

x = np.vstack((a,b))

print(x)

x = np.hstack((a,b))

print(x)

"""## Concatenating"""

a = np.arange(1,10).reshape(3,3)

b = np.arange(10,19).reshape(3,3)

print(a)

print(b)

np.concatenate((a,b))

np.concatenate((a,b), axis = 1)

"""# Broadcasting in NumPy arrays"""

a = np.arange(10,21,2)

b = np.array([[2],[2]])

print(a)

print(b)

z = a+b
print(z)

a = np.arange(10,21,2)

a+2

a - b

a*b

a = np.ones((3,3))
b = np.array([2])
print(a)

print(b)

a+b

a-b

"""# Arithmetic Operations on NumPy Array"""

a = np.eye(4)
print(a)

print(a+5)

a - 1

a*2

a/0.5

np.sin(a)

np.cos(a)

np.sqrt(a)

"""# Aggregate Function

## Mean, Median and Standard deviation
"""

a = np.arange(5,15,2)

print(a)

np.mean(a)

np.median(a)

np.std(a)

"""## Min-Max values"""

a = np.array([[1,6],[4,3]])
print(a)

print(np.min(a, axis = 0))

print(np.min(a, axis = 1))

print(np.max(a, axis = 1))

print(np.max(a, axis = 0))

"""# Sorting"""

a = np.array([1,4,3,10,20])

x = np.sort(a, kind = 'mergesort')

print(x)

"""# Matrix Multiplication"""

A = np.arange(0,9).reshape(3,3)
B = np.ones((3,3))

print(A)

print(B)

np.dot(A,B)

A.dot(B)

x=(1,6,4,3)
import numpy as np
x=np.array([1,6],[4,3])
print(a)
print(np.min(a,axis = 0))
print(np.min(a,axis = 1))
print(np.max(a,axis = 1))
print(np.max(a,axis = 0))

import numpy as np

a=(1,3,4,6)
print(a)
a=np.array(a)
print(np.min(a))

b=(1,2,3,4)
a=np.array(b)

print(np.max(a))
np.mean(a)
print(np.mean(a))

a=(2,4,6,8)